language: bash
services: docker

matrix:
  include:
    - os: linux
      env: VERSION=0.2
    - os: linux
      env: VERSION=0.3

script:
  - bash build-images.sh $VERSION

after_script:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; bash push-images.sh $VERSION
  on:
    branch: master
